name: build-app
run-name: build app from the ${{ github.head_ref }} branch
on: pull_request
jobs:
  build-pokemon-target:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup environment
        run: ./script/set-up-environment.sh
      - name: Build iOS Simulator
        run: ./script/build-ios-simulator.sh
